name: Frontend Deploy

on:
  push:
    paths:
      - 'Front/**'
      - '.github/workflows/front-deploy.yml'
    branches: ['develop']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install & Build React
        working-directory: Frontend
        run: |
          npm install
          CI='' npm run build

      - name: Copy Build Files to EC2 
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FRONT_AWS_IP }}
          username: ${{ secrets.FRONT_USERNAME }}
          key: ${{ secrets.FRONT_AWS_KEY }}
          source: "front/*"
          target: "/home/${{ secrets.FRONT_USERNAME }}/"

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONT_AWS_IP }}
          username: ${{ secrets.FRONT_USERNAME }}
          key: ${{ secrets.FRONT_AWS_KEY }}
          script: |
            sudo systemctl reload nginx
            sudo systemctl status nginx
